image: maven:3-eclipse-temurin-17

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Définit l'emplacement du cache de l'analyse Sonar
  GIT_DEPTH: "0"  # Permet de récupérer toute l'historique des branches, requis pour l'analyse

stages:
  - test
  - build-sonar

# Stage pour l'exécution des tests
test:
  stage: test
  script:
    - mvn clean test jacoco:report
  # Exécute les tests unitaires et génère les rapports JaCoCo
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/site/jacoco/jacoco.xml  # Ajoute le rapport JaCoCo comme artefact
    expire_in: 1 week  # Optionnel: conserver l'artefact pour une semaine

# Stage pour SonarQube
build-sonar:
  stage: build-sonar
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
  script:
    - mvn  verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
  allow_failure: true











