image: maven:3-eclipse-temurin-17

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

stages:
  - test
  - build-sonar

# Stage pour l'exécution des tests
test:
  stage: test
  script:
    - mvn clean test  # Exécute les tests unitaires (génère aussi les rapports JaCoCo)
  artifacts:
    paths:
      - target/site/jacoco/jacoco.xml
    expire_in: 1 week
# Stage pour SonarQube
build-sonar:
  stage: build-sonar
  
  cache:
    policy: pull-push
    key: "sonar-cache-$CI_COMMIT_REF_SLUG"
    paths:
      - "${SONAR_USER_HOME}/cache"
      - sonar-scanner/
      
  script: 
    - mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml 

  allow_failure: true

