name: Java CI with Maven and SonarQube

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache SonarQube and Maven dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.sonar
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run tests and generate JaCoCo report
      run: mvn clean test jacoco:report

    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/jacoco.xml

    - name: Run SonarQube analysis
      run: mvn verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
